
project_id = "dcnjjhavlvotzpwburvw"

[auth]
enable_signup = true
enable_confirmations = true
enable_recovery = true

[auth.email.template.confirmation]
subject = "Confirme seu email - CopyMaster"
content_path = ""

[auth.hook.send_email]
enabled = true
uri = "https://dcnjjhavlvotzpwburvw.supabase.co/functions/v1/send-confirmation-email"
secrets = ["RESEND_API_KEY"]

[functions.send-confirmation-email]
verify_jwt = false

[functions.handle-new-user]
verify_jwt = false

[functions.send-checkout-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
