
project_id = "dcnjjhavlvotzpwburvw"

[auth]
enable_signup = true
enable_confirmations = true
enable_recovery = true

[auth.email.template.confirmation]
subject = "Confirme seu email - CopyMaster"
content_path = ""

[functions.handle-new-user]
verify_jwt = false

[functions.send-checkout-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
