// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcnjjhavlvotzpwburvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjbmpqaGF2bHZvdHpwd2J1cnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTk0ODIsImV4cCI6MjA2NTI3NTQ4Mn0.-MFGhKOiKLY-ylXRJ-2oHYKgcKQM4w_-8wZbPZWxoJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);